# Generated by Django 5.2.15 on 2026-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_refresh_token_user_google_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_credentials',
            field=models.TextField(blank=True, null=True),
        ),
    ]
